<a href="https://colab.research.google.com/github/2303A51795/2303A51795-APPLICATION-OF-DATAMINING/blob/main/ASSIGNMENT_1_(PATIENT).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

IMPORT THE DATASET

In [2]:
df = pd.read_csv('/content/sample_data/patients.csv')

In [3]:
print(df)

    Patient_ID   Age  Glucose_Level  Blood_Pressure  Insulin        BMI
0          101  56.0          142.0            95.0    107.0        NaN
1          102  46.0          143.0            75.0    144.0  31.722504
2          103  33.0           79.0            92.0    195.0  31.572256
3          104  75.0          140.0            96.0     55.0  19.937204
4          105  70.0          115.0            83.0    152.0  29.576845
5          106  43.0          109.0            80.0      NaN  19.094712
6          107  62.0          100.0            62.0    131.0  30.445943
7          108  42.0           84.0           134.0      NaN  23.010526
8          109  60.0            NaN           102.0    187.0  33.052653
9          110  74.0          106.0            82.0     95.0  23.051127
10         111  62.0          138.0             NaN    178.0        NaN
11         112  58.0           81.0            91.0     63.0  25.353196
12         113  71.0           77.0           138.0    160.0  20.429946
13         114  30.0          128.0           136.0     53.0  34.380741
14         115  55.0          132.0           134.0     98.0  31.373887
15         116  39.0          146.0            80.0     54.0  28.525290
16         117  40.0          109.0           122.0     78.0  26.486267
17         118  79.0           89.0             NaN    124.0  20.886083
18         119  34.0           97.0           105.0     88.0  23.399749
19         120  55.0          107.0           139.0      NaN  33.557824
20         121  61.0           84.0            84.0    104.0  31.015059
21         122  51.0          126.0           131.0     97.0  20.594453
22         123  76.0          133.0           120.0    170.0  33.190730
23         124  72.0            NaN            83.0    147.0  33.894301
24         125  58.0           90.0           115.0     82.0  23.721735
25         126  61.0          113.0            90.0    116.0  34.020955
26         127  48.0           83.0           116.0     51.0  27.078134
27         128  43.0          110.0           109.0    169.0        NaN
28         129  41.0          140.0           120.0      NaN  24.255607
29         130  51.0           98.0           135.0    125.0  21.464697
30         131  63.0          145.0            77.0    126.0  27.301790
31         132  69.0           85.0           136.0    118.0  32.830554
32         133  63.0          108.0           116.0    175.0  25.075141
33         134  67.0           90.0           111.0    103.0  20.057697
34         135  74.0          142.0            88.0    182.0  23.932737
35         136  38.0           76.0            92.0    158.0  25.753378
36         137  69.0            NaN           129.0     91.0  28.710524
37         138  71.0          138.0            69.0     93.0  19.854395
38         139  30.0            NaN           125.0    177.0  24.207875
39         140  52.0           82.0             NaN     62.0  19.672875
40         141  59.0           88.0             NaN    132.0  32.532307
41         142  57.0           93.0            66.0     65.0        NaN
42         143  46.0            NaN             NaN     68.0  25.709724
43         144  51.0           92.0            90.0     72.0  34.113014
44         145  39.0           77.0           119.0      NaN  32.187204
45         146  61.0          142.0           135.0    186.0  29.240548
46         147  66.0          102.0           108.0     54.0  21.232747
47         148  30.0           89.0           130.0    143.0  34.140170
48         149  42.0           79.0           119.0    154.0        NaN
49         150  79.0          118.0           119.0    130.0  29.120890

CHECK ALL THE NA/NULL VALUES

In [4]:
df.isna()

    Patient_ID    Age  Glucose_Level  Blood_Pressure  Insulin    BMI
0        False  False          False           False    False   True
1        False  False          False           False    False  False
2        False  False          False           False    False  False
3        False  False          False           False    False  False
4        False  False          False           False    False  False
5        False  False          False           False     True  False
6        False  False          False           False    False  False
7        False  False          False           False     True  False
8        False  False           True           False    False  False
9        False  False          False           False    False  False
10       False  False          False            True    False   True
11       False  False          False           False    False  False
12       False  False          False           False    False  False
13       False  False          False           False    False  False
14       False  False          False           False    False  False
15       False  False          False           False    False  False
16       False  False          False           False    False  False
17       False  False          False            True    False  False
18       False  False          False           False    False  False
19       False  False          False           False     True  False
20       False  False          False           False    False  False
21       False  False          False           False    False  False
22       False  False          False           False    False  False
23       False  False           True           False    False  False
24       False  False          False           False    False  False
25       False  False          False           False    False  False
26       False  False          False           False    False  False
27       False  False          False           False    False   True
28       False  False          False           False     True  False
29       False  False          False           False    False  False
30       False  False          False           False    False  False
31       False  False          False           False    False  False
32       False  False          False           False    False  False
33       False  False          False           False    False  False
34       False  False          False           False    False  False
35       False  False          False           False    False  False
36       False  False           True           False    False  False
37       False  False          False           False    False  False
38       False  False           True           False    False  False
39       False  False          False            True    False  False
40       False  False          False            True    False  False
41       False  False          False           False    False   True
42       False  False           True            True    False  False
43       False  False          False           False    False  False
44       False  False          False           False     True  False
45       False  False          False           False    False  False
46       False  False          False           False    False  False
47       False  False          False           False    False  False
48       False  False          False           False    False   True
49       False  False          False           False    False  False

COUNT THE NO OF NA/NULL VALUES IN PARTICULAR ATTRIBUTES

In [5]:
df.isnull().sum()

Patient_ID        0
Age               0
Glucose_Level     5
Blood_Pressure    5
Insulin           5
BMI               5
dtype: int64

MEAN/MEDIAN/MODE OF ATTRIBUTES

In [9]:
Glucose_Level_Mean = df["Glucose_Level"].mean()
print(Glucose_Level_Mean)

107.66666666666667

In [10]:
Blood_Pressure_Median = df["Blood_Pressure"].median()
print(Blood_Pressure_Median)

109.0

In [21]:
Insulin_Mean = df["Insulin"].mean()
print(Insulin_Mean)

118.04444444444445

In [20]:
BMI_Mean = df["BMI"].mean()
print(BMI_Mean)

27.128133228004945

REPLACING THE NA/NULL VALUES WITH MEAN/MEDIAN/MODE OF ATTRIBUTES

In [22]:
df["Glucose_Level"].fillna(Glucose_Level_Mean, inplace=True)
df["Blood_Pressure"].fillna (Blood_Pressure_Median, inplace=True)
df["Insulin"].fillna (Insulin_Mean, inplace=True)
df["BMI"].fillna (BMI_Mean, inplace=True)

<ipython-input-22-9bc5b3d07467>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Glucose_Level"].fillna(Glucose_Level_Mean, inplace=True)
<ipython-input-22-9bc5b3d07467>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Blood_Pressure"].fillna (Blood_Pressure_Median, inplace=True)
<ipython-input-22-9bc5b3d07467>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Insulin"].fillna (Insulin_Mean, inplace=True)
<ipython-input-22-9bc5b3d07467>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["BMI"].fillna (BMI_Mean, inplace=True)

CHECK FOR ANY MORE NA/NULL VALUES

In [23]:
df.isnull().sum()

Patient_ID        0
Age               0
Glucose_Level     0
Blood_Pressure    0
Insulin           0
BMI               0
dtype: int64

In [24]:
df.isna()

    Patient_ID    Age  Glucose_Level  Blood_Pressure  Insulin    BMI
0        False  False          False           False    False  False
1        False  False          False           False    False  False
2        False  False          False           False    False  False
3        False  False          False           False    False  False
4        False  False          False           False    False  False
5        False  False          False           False    False  False
6        False  False          False           False    False  False
7        False  False          False           False    False  False
8        False  False          False           False    False  False
9        False  False          False           False    False  False
10       False  False          False           False    False  False
11       False  False          False           False    False  False
12       False  False          False           False    False  False
13       False  False          False           False    False  False
14       False  False          False           False    False  False
15       False  False          False           False    False  False
16       False  False          False           False    False  False
17       False  False          False           False    False  False
18       False  False          False           False    False  False
19       False  False          False           False    False  False
20       False  False          False           False    False  False
21       False  False          False           False    False  False
22       False  False          False           False    False  False
23       False  False          False           False    False  False
24       False  False          False           False    False  False
25       False  False          False           False    False  False
26       False  False          False           False    False  False
27       False  False          False           False    False  False
28       False  False          False           False    False  False
29       False  False          False           False    False  False
30       False  False          False           False    False  False
31       False  False          False           False    False  False
32       False  False          False           False    False  False
33       False  False          False           False    False  False
34       False  False          False           False    False  False
35       False  False          False           False    False  False
36       False  False          False           False    False  False
37       False  False          False           False    False  False
38       False  False          False           False    False  False
39       False  False          False           False    False  False
40       False  False          False           False    False  False
41       False  False          False           False    False  False
42       False  False          False           False    False  False
43       False  False          False           False    False  False
44       False  False          False           False    False  False
45       False  False          False           False    False  False
46       False  False          False           False    False  False
47       False  False          False           False    False  False
48       False  False          False           False    False  False
49       False  False          False           False    False  False

PRINT DF

ALL THE MISSING DATA HAS BEEN REPLACED

In [26]:
print(df)

    Patient_ID   Age  Glucose_Level  Blood_Pressure     Insulin        BMI
0          101  56.0     142.000000            95.0  107.000000  27.128133
1          102  46.0     143.000000            75.0  144.000000  31.722504
2          103  33.0      79.000000            92.0  195.000000  31.572256
3          104  75.0     140.000000            96.0   55.000000  19.937204
4          105  70.0     115.000000            83.0  152.000000  29.576845
5          106  43.0     109.000000            80.0  118.044444  19.094712
6          107  62.0     100.000000            62.0  131.000000  30.445943
7          108  42.0      84.000000           134.0  118.044444  23.010526
8          109  60.0     107.666667           102.0  187.000000  33.052653
9          110  74.0     106.000000            82.0   95.000000  23.051127
10         111  62.0     138.000000           109.0  178.000000  27.128133
11         112  58.0      81.000000            91.0   63.000000  25.353196
12         113  71.0      77.000000           138.0  160.000000  20.429946
13         114  30.0     128.000000           136.0   53.000000  34.380741
14         115  55.0     132.000000           134.0   98.000000  31.373887
15         116  39.0     146.000000            80.0   54.000000  28.525290
16         117  40.0     109.000000           122.0   78.000000  26.486267
17         118  79.0      89.000000           109.0  124.000000  20.886083
18         119  34.0      97.000000           105.0   88.000000  23.399749
19         120  55.0     107.000000           139.0  118.044444  33.557824
20         121  61.0      84.000000            84.0  104.000000  31.015059
21         122  51.0     126.000000           131.0   97.000000  20.594453
22         123  76.0     133.000000           120.0  170.000000  33.190730
23         124  72.0     107.666667            83.0  147.000000  33.894301
24         125  58.0      90.000000           115.0   82.000000  23.721735
25         126  61.0     113.000000            90.0  116.000000  34.020955
26         127  48.0      83.000000           116.0   51.000000  27.078134
27         128  43.0     110.000000           109.0  169.000000  27.128133
28         129  41.0     140.000000           120.0  118.044444  24.255607
29         130  51.0      98.000000           135.0  125.000000  21.464697
30         131  63.0     145.000000            77.0  126.000000  27.301790
31         132  69.0      85.000000           136.0  118.000000  32.830554
32         133  63.0     108.000000           116.0  175.000000  25.075141
33         134  67.0      90.000000           111.0  103.000000  20.057697
34         135  74.0     142.000000            88.0  182.000000  23.932737
35         136  38.0      76.000000            92.0  158.000000  25.753378
36         137  69.0     107.666667           129.0   91.000000  28.710524
37         138  71.0     138.000000            69.0   93.000000  19.854395
38         139  30.0     107.666667           125.0  177.000000  24.207875
39         140  52.0      82.000000           109.0   62.000000  19.672875
40         141  59.0      88.000000           109.0  132.000000  32.532307
41         142  57.0      93.000000            66.0   65.000000  27.128133
42         143  46.0     107.666667           109.0   68.000000  25.709724
43         144  51.0      92.000000            90.0   72.000000  34.113014
44         145  39.0      77.000000           119.0  118.044444  32.187204
45         146  61.0     142.000000           135.0  186.000000  29.240548
46         147  66.0     102.000000           108.0   54.000000  21.232747
47         148  30.0      89.000000           130.0  143.000000  34.140170
48         149  42.0      79.000000           119.0  154.000000  27.128133
49         150  79.0     118.000000           119.0  130.000000  29.120890

NOW TO SCALE USING MIN MAX SCALING USING SKLEARN LIBRARY

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
scaler = MinMaxScaler()

In [31]:
df[['Age', 'Glucose_Level']] = scaler.fit_transform(df[['Age', 'Glucose_Level']])

In [32]:
df['Blood_Pressure'] = (df['Blood_Pressure'] - df['Blood_Pressure'].min()) / (df['Blood_Pressure'].max() - df['Blood_Pressure'].min())

In [33]:
from sklearn.preprocessing import StandardScaler

s_scaler = StandardScaler()

In [34]:
df[['BMI']] = s_scaler.fit_transform(df[[ 'BMI']])

In [35]:
df['BMI']

0     0.000000
1     0.973303
2     0.941474
3    -1.523376
4     0.518752
5    -1.701855
6     0.702868
7    -0.872302
8     1.255091
9    -0.863701
10    0.000000
11   -0.376015
12   -1.418990
13    1.536443
14    0.899450
15    0.295983
16   -0.135977
17   -1.322359
18   -0.789847
19    1.362110
20    0.823433
21   -1.384140
22    1.284342
23    1.433392
24   -0.721635
25    1.460223
26   -0.010592
27    0.000000
28   -0.608536
29   -1.199781
30    0.036789
31    1.208040
32   -0.434920
33   -1.497850
34   -0.676935
35   -0.291238
36    0.335225
37   -1.540919
38   -0.618648
39   -1.579373
40    1.144858
41    0.000000
42   -0.300486
43    1.479725
44    1.071749
45    0.447509
46   -1.248919
47    1.485478
48    0.000000
49    0.422159
Name: BMI, dtype: float64

In [38]:
df['Insulin'] = (df['Insulin'] - Insulin_Mean) / df['Insulin'].std()

In [39]:
df

    Patient_ID       Age  Glucose_Level  Blood_Pressure     Insulin       BMI
0          101  0.530612       0.942857        0.428571 -118.309327  0.000000
1          102  0.326531       0.957143        0.168831 -117.421944  0.973303
2          103  0.061224       0.042857        0.389610 -116.198796  0.941474
3          104  0.918367       0.914286        0.441558 -119.556459 -1.523376
4          105  0.816327       0.557143        0.272727 -117.230078  0.518752
5          106  0.265306       0.471429        0.233766 -118.044444 -1.701855
6          107  0.653061       0.342857        0.000000 -117.733727  0.702868
7          108  0.244898       0.114286        0.935065 -118.044444 -0.872302
8          109  0.612245       0.452381        0.519481 -116.390662  1.255091
9          110  0.897959       0.428571        0.259740 -118.597126 -0.863701
10         111  0.653061       0.885714        0.610390 -116.606512  0.000000
11         112  0.571429       0.071429        0.376623 -119.364592 -0.376015
12         113  0.836735       0.014286        0.987013 -117.038212 -1.418990
13         114  0.000000       0.742857        0.961039 -119.604425  1.536443
14         115  0.510204       0.800000        0.935065 -118.525176  0.899450
15         116  0.183673       1.000000        0.233766 -119.580442  0.295983
16         117  0.204082       0.471429        0.779221 -119.004843 -0.135977
17         118  1.000000       0.185714        0.610390 -117.901611 -1.322359
18         119  0.081633       0.300000        0.558442 -118.765010 -0.789847
19         120  0.510204       0.442857        1.000000 -118.044444  1.362110
20         121  0.632653       0.114286        0.285714 -118.381277  0.823433
21         122  0.428571       0.714286        0.896104 -118.549160 -1.384140
22         123  0.938776       0.814286        0.753247 -116.798378  1.284342
23         124  0.857143       0.452381        0.272727 -117.349994  1.433392
24         125  0.571429       0.200000        0.688312 -118.908909 -0.721635
25         126  0.632653       0.528571        0.363636 -118.093477  1.460223
26         127  0.367347       0.100000        0.701299 -119.652392 -0.010592
27         128  0.265306       0.485714        0.610390 -116.822362  0.000000
28         129  0.224490       0.914286        0.753247 -118.044444 -0.608536
29         130  0.428571       0.314286        0.948052 -117.877627 -1.199781
30         131  0.673469       0.985714        0.194805 -117.853644  0.036789
31         132  0.795918       0.128571        0.961039 -118.045510  1.208040
32         133  0.673469       0.457143        0.701299 -116.678462 -0.434920
33         134  0.755102       0.200000        0.636364 -118.405260 -1.497850
34         135  0.897959       0.942857        0.337662 -116.510579 -0.676935
35         136  0.163265       0.000000        0.389610 -117.086178 -0.291238
36         137  0.795918       0.452381        0.870130 -118.693060  0.335225
37         138  0.836735       0.885714        0.090909 -118.645093 -1.540919
38         139  0.000000       0.452381        0.818182 -116.630495 -0.618648
39         140  0.448980       0.085714        0.610390 -119.388576 -1.579373
40         141  0.591837       0.171429        0.610390 -117.709744  1.144858
41         142  0.551020       0.242857        0.051948 -119.316626  0.000000
42         143  0.326531       0.452381        0.610390 -119.244676 -0.300486
43         144  0.428571       0.228571        0.363636 -119.148742  1.479725
44         145  0.183673       0.014286        0.740260 -118.044444  1.071749
45         146  0.632653       0.942857        0.948052 -116.414646  0.447509
46         147  0.734694       0.371429        0.597403 -119.580442 -1.248919
47         148  0.000000       0.185714        0.883117 -117.445928  1.485478
48         149  0.244898       0.042857        0.740260 -117.182111  0.000000
49         150  1.000000       0.600000        0.740260 -117.757711  0.422159